cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('list/', views.list, name='list'), 
    path('add/', views.add, name='add'), 
    path('delete/', views.delete, name='delete'),
    path('rental_review/', views.rental_review, name='rental_review'),
    path('thank_you/', views.thank_you, name='thank_you')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include # app의 urls.py 연결 위해 import
from django.http.response import HttpResponse
from . import views # 프로젝트 레벨의 Views.py import

def home_view (request):
    return HttpResponse("HOME PAGE")

urlpatterns = [
    #path('', home_view, name='home'), # 프로젝트 레벨의 urls.py의 home_view 연결
    path('', views.home_view, name='home'), # 프로젝트 레벨의 views.py의 home_view 연결
    path('my_app/', include('my_app.urls')), # my_app의 urls.py 연결
    path('cars/', include('cars.urls')), # cars의 urls.py 연결
    path('classroom/', include('classroom.urls')),
    path('admin/', admin.site.urls)
]

handler404 = 'config.views.my_custom_page_not_found_view'

my_app/urls.py
from django.urls import path
from . import views

# app namespace 등록
app_name = "my_app"

urlpatterns = [
    path('', views.simple_view, name='example'), # domain.com/my_app
    path('variable', views.variable_view, name='variable'),
    path('patient', views.list_patient, name='list_patient')
]

# urlpatterns = [
    #path('', views.index, name="index"), #/my_apps --> Project urls.py,
    # path('<int:num_page>', views.num_page_view), # /my_apps/num_page
    # path('<str:topic>', views.news_view, name="topic-page"), # /my_apps/topic   
    #path('<int:num1>/<int:num2>', views.add_view) # /my_apps/topic
# ]

my_app/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Patient(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(120)])
    heartrate = models.IntegerField(default=60, validators=[MinValueValidator(10), MaxValueValidator(300)])

    def __str__(self):
        return  f"{self.last_name}, {self.first_name} is {self.age} years old."

my_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound, Http404,  HttpResponseRedirect
from django.urls import reverse
from . import models
#from .models import patient

def simple_view(request):
    return render(request,'my_app/example.html')

def variable_view(request):

    # 템플릿으로 전달할 딕셔너리
    my_var = { 
        'first_name': 'Rosalind',
        'last_name': 'Franklin',
        'some_list': [1, 2, 3],
        'some_dict': {'inside_key':'inside_value'},
        'user_logged_in': True
    }

    return render(request,'my_app/variable.html', context=my_var)

def list_patient(request):

    all_patients = models.Patient.objects.all()
    context_dict = {'patients': all_patients}

    return render(request, 'my_app/list.html', context=context_dict)

# articles = {
#     'sports' : 'Sports Page',
#     'finance' : 'Finance Page',
#     'politics' : 'PoIitics Page'
# }

# # def index(request):
# #     return HttpResponse("Hello This is a View Inside My_App")

# def news_view(request, topic):
#     try:
#         result = articles[topic]
#         return HttpResponse(articles[topic])
#     except:
#         result = "Topic Not Found"
#         #return HttpResponseNotFound(result)
#         raise Http404("404 Generic Error") # 추후 404.html에 연결

# def add_view(request, num1, num2):
#     # domain.com/my_app/num1/num2 --> num1+num2
#     result = num1 + num2
#     return HttpResponse(str(result))

# # Redirect
# # domain/com/my_app/0 --> domain/com/my_app/sports

# def num_page_view(request, num_page):
#     topics_list = list(articles.keys()) # ['sports', 'finance', 'politics']
#     topic = topics_list[num_page]

#     # webpage = reverse('topic-page', args=[topic]) # 첫번째 인자는 urls.py에 정의한 name
#     # return HttpResponseRedirect(webpage)
#     return HttpResponseRedirect(reverse('topic-page', args=[topic]))

my_app/templates/my_app/example.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h2> example.html의 Block 안쪽 입니다. </h2>
<img src="{% static "my_app/poke.jpg" %}" alt="poke image">

{% endblock  %}


{% comment %} <html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>EXAMPLE HTML CONNECTED</h1>
    <h1><a href="{% url 'my_app:variable' %}">Variable</a></h1>
</body>
</html> {% endcomment %}

my_app/templates/my_app/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
    {% for person in patients %}
        <li>{{person}}</li>
        <li>{{person.last_name}}</li>
    {% endfor %}
    </ul>
</body>
</html>

my_app/templates/my_app/variable.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>VARIABLE.HTML</h1>

    <ul>
    {% for num in some_list %}
        {% if num == 2 %}
            <li> Two </li>
        {% else %}
            <li>{{num}}</li>
        {% endif %}
    {% endfor %}
    </ul>

    {% comment %} {% if user_logged_in %}
    <h1>Welcome Back</h1>
    {% endif %} 
    <ul>{% endcomment %}

    {% comment %} <ul>
    {% for element in some_list %}
        <li>{{element}}</li>
    {% endfor %}
    </ul> {% endcomment %}

    {% comment %} 
    <h2>{{first_name}} {{last_name}}</h2>
    <h2>{{some_list}}</h2>
    <h2>{{some_list.0}}</h2> <!-- list . index -->
    <h2>{{some_dict}}</h2>
    <h2>{{some_dict.inside_key | upper}}</h2> <!-- dict . key --> 
     {% endcomment %}
</body>
</html>