cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('list/', views.list, name='list'), 
    path('add/', views.add, name='add'), 
    path('delete/', views.delete, name='delete'),
    path('rental_review/', views.rental_review, name='rental_review'),
    path('thank_you/', views.thank_you, name='thank_you')
]

classroom/urls.py
from django.urls import path
#from .views import home_view
from .views import HomeView, ThankuView, ContactFormView,TeacherCreateView,TeacherListView, TeacherDetailView, TeacherUpdateView, TeacherDeleteView

app_name = 'classroom'

urlpatterns = [
    #path('',home_view,name='home')
    path('',HomeView.as_view(),name='home'),
    path('thanku/',ThankuView.as_view(),name='thanku'),
    path('contact/',ContactFormView.as_view(),name='contact'),
    path('create_teacher/',TeacherCreateView.as_view(),name='create_teacher'),
    path('list_teacher/',TeacherListView.as_view(),name='list_teacher'),
    path('teacher_detail/<int:pk>', TeacherDetailView.as_view(), name='detail_teacher'),
    path('update_teacher/<int:pk>', TeacherUpdateView.as_view(), name='update_teacher'),
    path('delete_teacher/<int:pk>', TeacherDeleteView.as_view(), name='delete_teacher')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include # app의 urls.py 연결 위해 import
from django.http.response import HttpResponse
from . import views # 프로젝트 레벨의 Views.py import

def home_view (request):
    return HttpResponse("HOME PAGE")

urlpatterns = [
    #path('', home_view, name='home'), # 프로젝트 레벨의 urls.py의 home_view 연결
    path('', views.home_view, name='home'), # 프로젝트 레벨의 views.py의 home_view 연결
    path('my_app/', include('my_app.urls')), # my_app의 urls.py 연결
    path('cars/', include('cars.urls')), # cars의 urls.py 연결
    path('classroom/', include('classroom.urls')),
    path('admin/', admin.site.urls)
]

handler404 = 'config.views.my_custom_page_not_found_view'

classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.last_name} teaches {self.subject}"

classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

classroom/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView
from .forms import ContactForm
from .models import Teacher

# Create your views here.
# def home_view(request):
#    return render(request, 'classroom/home.html')

class HomeView(TemplateView):
    template_name = "classroom/home.html"

class ThankuView(TemplateView):
    template_name = "classroom/thanku.html" 

class TeacherCreateView(CreateView):
    # Template = [model]_form.html
    # Model에 연결
    model = Teacher 
    # 표시하려는 속성
    fields = '__all__'
    # 성공 후 이동되는 URL
    success_url = reverse_lazy('classroom:thanku')

class ContactFormView(FormView):
    form_class = ContactForm
    template_name = "classroom/contact.html" 

    # Success URL (Not HTML file)
    # success_url = "/classroom/thanku/" 
    success_url = reverse_lazy('classroom:thanku')

    # What to do with form
    def form_valid(self, form):
        #form.save()
        print(form.cleaned_data)
        return super().form_valid(form)
    
class TeacherListView(ListView):
    # Template = [model]_list.html
    # Model에 연결
    model = Teacher 
    context_object_name = "teacher_list" # default = object_list


class TeacherDetailView(DetailView):
    # Template = [model]_detail.html
    # Model에 연결
    model = Teacher 


class TeacherUpdateView(UpdateView):
    # Template = [model]_form.html
    # Model에 연결
    model = Teacher 
    fields = ['subject']

    # 성공 후 이동되는 URL
    success_url = reverse_lazy('classroom:list_teacher')

class TeacherDeleteView(DeleteView):
    # Template = [model]_confirm_delete.html
    # Model에 연결
    model = Teacher
    success_url = reverse_lazy('classroom:list_teacher')

classroom/templates/classroom/contact.html
<h1>Form View Template(contact.html)</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

classroom/templates/classroom/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>WELCOME TO HOME.HMTL</h1>
    <ul>
        <li>
            <!-- # urls.py의 app_name/(path)name -->
            <a href="{% url "classroom:thanku" %}">Thank You</a> 
        </li>
        <li>
            <a href="{% url "classroom:contact" %}">Contact</a> 
        </li>
        <li>
            <a href="{% url "classroom:create_teacher" %}">Register Teacher</a> 
        </li>
        <li>
            <a href="{% url "classroom:list_teacher" %}">Teacher List</a> 
        </li>
    </ul>
</body>
</html>

classroom/templates/classroom/teacher_confirm_delete.html
<h1>정말 삭제하시겠습니까?</h1>
<h2>{{teacher}}</h2>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete">
</form>

classroom/templates/classroom/teacher_detail.html
<h1>DetailView for Teacher</h1>
{{teacher}}

classroom/templates/classroom/teacher_form.html
<h1>Teacher Form</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

classroom/templates/classroom/teacher_list.html
<h1>List of Teachers (ListView)</h1>
<ul>
    {% for teacher in teacher_list %}
        <li>
            <a href="/classroom/teacher_detail/{{teacher.id}}">{{teacher.first_name}} {{teacher.last_name}}</a>
            <ul>
                <li><a href="/classroom/update_teacher/{{teacher.id}}">Update</a></li>
                <li><a href="/classroom/delete_teacher/{{teacher.id}}">Delete</a></li>
            </ul>            
        </li>
    {% endfor %}
</ul>

classroom/templates/classroom/thanku.html
<h1>THANK U</h1>