cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('list/', views.list, name='list'), 
    path('add/', views.add, name='add'), 
    path('delete/', views.delete, name='delete'),
    path('rental_review/', views.rental_review, name='rental_review'),
    path('thank_you/', views.thank_you, name='thank_you')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include # app의 urls.py 연결 위해 import
from django.http.response import HttpResponse
from . import views # 프로젝트 레벨의 Views.py import

def home_view (request):
    return HttpResponse("HOME PAGE")

urlpatterns = [
    #path('', home_view, name='home'), # 프로젝트 레벨의 urls.py의 home_view 연결
    path('', views.home_view, name='home'), # 프로젝트 레벨의 views.py의 home_view 연결
    path('my_app/', include('my_app.urls')), # my_app의 urls.py 연결
    path('cars/', include('cars.urls')), # cars의 urls.py 연결
    path('classroom/', include('classroom.urls')),
    path('admin/', admin.site.urls)
]

handler404 = 'config.views.my_custom_page_not_found_view'

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base Title</title>
</head>
<body>
    <h1>Base.html의 BLOCK 위쪽 입니다.</h1>
    {% block content %}
    
    {% endblock  %}
    <h1>Base.html의 BLOCK 아래쪽 입니다.</h1>
</body>
</html>

templates/base_cars.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>    
</head>
<body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url "cars:list" %}">LIST</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "cars:add" %}">ADD</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "cars:delete" %}">DELETE</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    {% block content %}
    {% endblock %}
</body>
</html>

templates/error_view.html
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>MY CUSTOM 404 PAGE</h1>
    </body>
</html>